[package]
name = "enums-derive"
version = "0.1.0"
authors = ["Weston Carvalho <carvalhoweston@gmail.com>"]

[dependencies]
proc-macro2 = "0.4.2"
quote = "0.6.0"
syn = "0.14.0"

[lib]
proc-macro = true